services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - ${OLLAMA_PORT}:11434
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_KEEP_ALIVE=24h
    volumes:
      - ${DATA_DIR}/ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]

  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - ${DATA_DIR}/open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
  
  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    container_name: ollama-open-webui-pipelines
    ports:
      - 9099:9099
    environment:
      # Example pipeline
      # - PIPELINES_URLS="https://github.com/open-webui/pipelines/blob/main/examples/filters/detoxify_filter_pipeline.py"
      - ADD_HOST=host.docker.internal:host-gateway
    volumes:
      - ${DATA_DIR}/pipelines:/app/pipelines
