services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8088:8088
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - ./gluetun-files:/gluetun
    env_file:
      - .env
    environment:
      # Timezone for accurate log times
      - TZ=Asia/Singapore
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    depends_on:
      - gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
      - WEBUI_PORT=8088
      - TORRENTING_PORT=6881
    volumes:
      - ./appdata:/config
      - /mnt/NAS/downloads/qbittorrent:/downloads #optional
    network_mode: service:gluetun
    restart: unless-stopped
networks: {}
