services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    # Uncomment below to expose Ollama API outside the container stack
    # ports:
    #   - ${OLLAMA_PORT}:11434
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_KEEP_ALIVE=24h
    env_file: ".env"
    volumes:
      - ${STACKS_DIR}/ollama:/root/.ollama
#      - ${MODELS_DIR}:/root/.ollama/models
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]

  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - ${STACKS_DIR}/open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:${PORT}
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
    env_file: ".env"
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks: 
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.open-webui.entrypoints=http-external"
      - "traefik.http.routers.open-webui.rule=Host(`chatbot.YOUR_DOMAIN.co.uk`)"
      - "traefik.http.middlewares.open-webui-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.open-webui.middlewares=open-webui-https-redirect"
      - "traefik.http.routers.open-webui-secure.entrypoints=https-external"
      - "traefik.http.routers.open-webui-secure.rule=Host(`chatbot.YOUR_DOMAIN.co.uk`)"
      - "traefik.http.routers.open-webui-secure.tls=true"
      - "traefik.http.routers.open-webui-secure.service=open-webui"
      - "traefik.http.services.open-webui.loadbalancer.server.port=${PORT}"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true    
  
  # pipelines:
  #   image: ghcr.io/open-webui/pipelines:main
  #   container_name: ollama-open-webui-pipelines
  #   ports:
  #     - 9099:9099
  #   environment:
  #     # Example pipeline
  #     # - PIPELINES_URLS="https://github.com/open-webui/pipelines/blob/main/examples/filters/detoxify_filter_pipeline.py"
  #     - ADD_HOST=host.docker.internal:host-gateway
  #   env_file: ".env"
  #   volumes:
  #     - ${STACKS_DIR}/pipelines:/app/pipelines
