services:
  vaultwarden:
    container_name: vaultwarden
    image: ${VAULTWARDEN_IMAGE_TAG}
    volumes:
      - ${VAULTWARDEN_DATA}:/data
    environment:
      WEBSOCKET_ENABLED: "true"
      SIGNUPS_ALLOWED: ${VAULTWARDEN_SIGNUPS_ALLOWED}
    env_file:
      - .env
    networks:
      - proxy
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:80/
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    labels:
      - traefik.enable=true
      - traefik.http.routers.vaultwarden.entrypoints=http
      - traefik.http.routers.vaultwarden.rule=Host(`${VAULTWARDEN_HOSTNAME}`)
      - traefik.http.middlewares.vaultwarden-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.vaultwarden.middlewares=vaultwarden-https-redirect
      - traefik.http.routers.vaultwarden-secure.entrypoints=https
      - traefik.http.routers.vaultwarden-secure.rule=Host(`${VAULTWARDEN_HOSTNAME}`)
      - traefik.http.routers.vaultwarden-secure.tls=true
      - traefik.http.routers.vaultwarden-secure.service=vaultwarden
      - traefik.http.services.vaultwarden.loadbalancer.server.port=80
      - traefik.docker.network=proxy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
networks:
  proxy:
    external: true
