services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp" # DNS
      - "53:53/udp" # DNS
      - "67:67/udp" # DHCP
      - "8888:8888/tcp" # web interface
    #  - "443:443/tcp"
    networks:
    #   pihole_internal:
    #     ipv4_address: 172.70.9.3
      proxy:
    environment:
      TZ: 'Asia/Singapore'
      PIHOLE_DNS_: 9.9.9.9;149.112.112.112;1.1.1.1;1.0.0.1 # Quad9 and Cloudflare
      DNSMASQ_LISTENING: 'all'
    env_file:
      - .env
    # Volumes store your data between container upgrades
    volumes:
      - ${STACKS_DIR}:/etc/pihole
      - ${STACKS_DIR}/etc-dnsmasq.d/:/etc/dnsmasq.d/
      - ${STACKS_DIR}/custom-port.conf:/etc/lighttpd/conf-enabled/20-custom-port.conf
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    # cap_add:
    #   - NET_ADMIN
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.entrypoints=http"
      - "traefik.http.routers.pihole.rule=Host(`pihole.YOUR_DOMAIN.com`)"
      - "traefik.http.middlewares.pihole-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.pihole.middlewares=pihole-https-redirect"
      - "traefik.http.routers.pihole-secure.entrypoints=https"
      - "traefik.http.routers.pihole-secure.rule=Host(`pihole.YOUR_DOMAIN.com`)"
      - "traefik.http.routers.pihole-secure.tls=true"
      - "traefik.http.routers.pihole-secure.service=pihole"
      - "traefik.http.services.pihole.loadbalancer.server.port=${PORT}"
      - "traefik.docker.network=proxy"
      - "traefik.http.middlewares.pihole-addprefix.addprefix.prefix=/admin"
      - "traefik.http.middlewares.pihole-redirectregex.redirectregex.regex=/admin/$"
      - "traefik.http.middlewares.pihole-redirectregex.redirectregex.replacement=/"

networks:
  # pihole_internal:
  #    ipam:
  #      config:
  #        - subnet: 172.70.9.0/29
  #    name: pihole_internal
  proxy:
    external: true