http: # extra config for handling ssl termination for better security
  middlewares:    
    default-security-headers:
      headers:
        browserXssFilter: true                            # X-XSS-Protection=1; mode=block
        contentTypeNosniff: true                          # X-Content-Type-Options=nosniff
        forceSTSHeader: true                              # Add the Strict-Transport-Security header even when the connection is HTTP
        frameDeny: false                                   # X-Frame-Options=deny
        referrerPolicy: "strict-origin-when-cross-origin"
        stsIncludeSubdomains: true                        # Add includeSubdomains to the Strict-Transport-Security header
        stsPreload: true                                  # Add preload flag appended to the Strict-Transport-Security header
        stsSeconds: 3153600                              # Set the max-age of the Strict-Transport-Security header (63072000 = 2 years)
        contentSecurityPolicy: "default-src 'self'"     
        customRequestHeaders:
          X-Forwarded-Proto: https
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true
    crowdsec-bouncer:
      forwardauth:
        address: http://bouncer-traefik:8080/api/v1/forwardAuth
        trustForwardHeader: true

  # routers:
  #   jellyfin:
  #     entryPoints:
  #       - "https"
  #     rule: "Host(`jellyfin.auggie.space`)"
  #     middlewares:
  #       - default-security-headers
  #       - https-redirectscheme
  #     tls: {}
  #     service: jellyfin
  #   portainer:
  #     entryPoints:
  #       - "https"
  #     rule: "Host(`portainer-demo.jimsgarage.co.uk`)"
  #     middlewares:
  #       - default-security-headers
  #       - https-redirectscheme
  #     tls: {}
  #     service: portainer

  # services:
  #   jellyfin:
  #     loadBalancer:
  #       servers:
  #         - url: "http://192.168.1.131:30013"
  #       passHostHeader: true
  #   portainer:
  #     loadBalancer:
  #       servers:
  #         - url: "https://192.168.200.122:9443"
  #       passHostHeader: true
    