services:  
  byparr:
    container_name: byparr
    hostname: byparr
    image: ghcr.io/thephaseless/byparr:latest
    shm_size: 2gb
    volumes:
      - ./configs/mediarr/byparr/screenshots:/app/screenshots
    networks:
      - mediarr
    env_file:
      - .env
    environment:
      - PUID=568
      - PGID=568
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TIMEZONE:-Asia/Singapore}
    restart: unless-stopped