services:
  jellyseerr:
    container_name: jellyseerr
    image: ghcr.io/fallenbagel/jellyseerr:latest
    restart: unless-stopped
    user: 568:568
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - TZ=${TIMEZONE:-Asia/Singapore}
      - PORT=5055
    networks:
      - mediarr
    ports:
      - 5055:5055
    volumes:
      - ./configs/mediarr/jellyseerr:/app/config
    depends_on:
      - sonarr
      - radarr
  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    networks:
      - mediarr
    environment:
      - PUID=568
      - PGID=568
      - TZ=${TIMEZONE:-Asia/Singapore}
    volumes:
      - ./configs/mediarr/sonarr:/config
      - /mnt/NAS/data/:/data/
    depends_on:
      - prowlarr
      - qbittorrent
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    networks:
      - mediarr
    environment:
      - PUID=568
      - PGID=568
      - TZ=${TIMEZONE:-Asia/Singapore}
    volumes:
      - ./configs/mediarr/radarr:/config
      - /mnt/NAS/data/:/data/
    ports:
      - 7878:7878
    restart: unless-stopped
    depends_on:
      - prowlarr
      - qbittorrent
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    hostname: prowlarr
    networks:
      - mediarr
    environment:
      - PUID=568
      - PGID=568
      - TZ=${TIMEZONE:-Asia/Singapore}
    volumes:
      - ./configs/mediarr/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    depends_on:
      - byparr
  byparr:
    container_name: byparr
    hostname: byparr
    image: ghcr.io/thephaseless/byparr:latest
    shm_size: 2gb
    volumes:
      - ./configs/mediarr/byparr/screenshots:/app/screenshots
    networks:
      - mediarr
    env_file:
      - .env
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TIMEZONE:-Asia/Singapore}
    restart: unless-stopped
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8088:8088
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - ./gluetun/gluetun-files:/gluetun
    env_file:
      - .env
    environment:
      # Timezone for accurate log times
      - TZ=Asia/Singapore
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    depends_on:
      - gluetun
    environment:
      - PUID=568
      - PGID=568
      - TZ=${TIMEZONE:-Asia/Singapore}
      - WEBUI_PORT=8088
      - TORRENTING_PORT=6881
    volumes:
      - ./gluetun/appdata:/config
      - /mnt/NAS/data/torrents/:/data/torrents/
    network_mode: service:gluetun
    restart: unless-stopped
networks:
  mediarr:
    external: true
