services:
  jellyseerr:
    container_name: jellyseerr
    image: ghcr.io/fallenbagel/jellyseerr:2.7.2
    restart: unless-stopped
    user: 568:568
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - TZ=${TIMEZONE:-Asia/Singapore}
      - PORT=5055
    networks:
      - mediarr
    ports:
      - 5055:5055
    volumes:
      - ./configs/mediarr/jellyseerr:/app/config
    depends_on:
      - sonarr
      - radarr
  sonarr:
    image: ghcr.io/linuxserver/sonarr:version-4.0.15.2941
    container_name: sonarr
    hostname: sonarr
    networks:
      - mediarr
    environment:
      - PUID=568
      - PGID=568
      - TZ=${TIMEZONE:-Asia/Singapore}
    volumes:
      - ./configs/mediarr/sonarr:/config
      - /mnt/NAS/data/:/data/
    depends_on:
      - prowlarr
      - qbittorrent
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:5.26.2.10099-ls279
    container_name: radarr
    hostname: radarr
    networks:
      - mediarr
    environment:
      - PUID=568
      - PGID=568
      - TZ=${TIMEZONE:-Asia/Singapore}
    volumes:
      - ./configs/mediarr/radarr:/config
      - /mnt/NAS/data/:/data/
    ports:
      - 7878:7878
    restart: unless-stopped
    depends_on:
      - prowlarr
      - qbittorrent
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    hostname: bazarr
    networks:
      - mediarr
    environment:
      - PUID=568
      - PGID=568
      - TZ=${TIMEZONE:-Asia/Singapore}
    volumes:
      - ./configs/mediarr/bazarr:/config
      - /mnt/NAS/data/:/data/
    ports:
      - 6767:6767
    restart: unless-stopped
    depends_on:
      - sonarr
      - radarr
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    hostname: prowlarr
    networks:
      - mediarr
    environment:
      - PUID=568
      - PGID=568
      - TZ=${TIMEZONE:-Asia/Singapore}
    volumes:
      - ./configs/mediarr/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    depends_on:
      - flaresolverr
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    hostname: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TIMEZONE:-Asia/Singapore}
    ports:
      - "${PORT:-8191}:8191"
    networks:
      - mediarr
    restart: unless-stopped
  gluetun:
    image: ghcr.io/qdm12/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8088:8088
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - ./gluetun/gluetun-files:/gluetun
    env_file:
      - .env
    environment:
      - TZ=${TIMEZONE:-Asia/Singapore}
    restart: unless-stopped
    networks:
      gluetun-network:
        ipv4_address: 172.16.11.10
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
      - PUID=568
      - PGID=568
      - TZ=${TIMEZONE:-Asia/Singapore}
      - WEBUI_PORT=8088
    volumes:
      - ./gluetun/appdata:/config
      - /mnt/NAS/data/torrents/:/data/torrents/
    network_mode: service:gluetun
    restart: unless-stopped
networks:
  gluetun-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.11.0/24
          gateway: 172.16.11.254
  mediarr:
    external: true
    ipam:
      config:
        - subnet: 172.16.10.0/24
